# Generated by Django 3.1.2 on 2020-11-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epdf', '0002_auto_20201102_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=225)),
                ('lname', models.CharField(default='', max_length=225)),
                ('email', models.EmailField(default='', max_length=225)),
                ('password', models.CharField(default='', max_length=225)),
            ],
        ),
    ]
